version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - app_storage:/home/node/app/storage
    restart: always

volumes:
  app_storage: