version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../:/home/node/app
      - node_modules:/home/node/app/node_modules
      - pnpm-store:/pnpm  # Add pnpm store volume
    working_dir: /home/node/app/
    command: sleep infinity
    depends_on:
      - mongo
    env_file:
      - ../.env
    environment:
      - PNPM_HOME=/pnpm

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
  pnpm-store:  # Add pnpm store volume